use_frameworks!

platform :ios, '13.0'

target 'example' do
   pod 'ActiveLookSDK', :path => '/Users/geoffreygoutallier/Documents/2.Professionnel/LaChouette/microoled/ActiveLook/SDK/iOS/ios-sdk',
                        :branch => 'feat/add-swiftlint' # :branch => 'feat/firmware-manager'
end
